language: php

jobs:
    include:
        - php: '7.2'
          env: COVERAGE="--coverage-clover phpunit-coverage.xml"
        - php: '7.3'
        - php: '7.4'

    allow_failures:
        - php: '7.2'
          env: DEPS="--prefer-stable --prefer-lowest"

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [[ $COVERAGE == "" ]]; then phpenv config-rm xdebug.ini || true; fi

install:
    - composer update --prefer-dist --no-progress --no-suggest --ansi ${DEPS}

script:
    - ./vendor/bin/phpunit ${COVERAGE}

after_success:
    - if [[ $COVERAGE != "" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ $COVERAGE != "" ]]; then php ocular.phar code-coverage:upload --format=php-clover phpunit-coverage.xml; fi
